
"use client"

import { useEffect, useState } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleAnalytics } from "@next/third-parties/google";
import { ThemeContext } from "./hooks/ThemeContext";
import { Helmet } from "react-helmet";
import { Toaster } from "@/components/ui/sonner"; // Ensure correct import path

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [theme, setIsDark] = useState<boolean>(false);

  useEffect(() => {
    // This code runs only on the client
    const storedTheme = localStorage.getItem("theme");
    setIsDark(storedTheme ? JSON.parse(storedTheme) : false);
  }, []);

  const toggleTheme = () => {
    const newTheme = !theme;
    setIsDark(newTheme);
    localStorage.setItem("theme", JSON.stringify(newTheme));
  };

  return (
    <html lang="en">
      <body className={`${inter.className} ${theme ? "dark" : ""}`}>
        <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS ?? ''} />
        <Helmet>
          <title>Annuar Ndung'u</title>
          <meta name="description" content="Generated by create next app" />
        </Helmet>
        <Toaster position="top-right" />
        <ThemeContext.Provider value={{ theme, toggleTheme }}>
          {children}
        </ThemeContext.Provider>
      </body>
    </html>
  );
}

